### ISSUE TITLE
Failed to determine git version (git version 1.9.3 (Apple Git-50))

### ISSUE THREAD

**Issue by andygrunwald** [MetricsGrimoire/RepositoryHandler#20]
I got this error during the comment `./cvsanaly2 -f ./config ../teeeeeest`:

```
Parsing log for ../teeeeeest (git)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/agrunwald/Development/CVSAnaly.git/pycvsanaly2/Log.py", line 71, in _logreader
    repo.log(self.uri or repo.get_uri(), files=self.files, gitref=self.gitref)
  File "/Library/Python/2.7/site-packages/repositoryhandler/backends/git.py", line 287, in log
    major, minor, micro, extra = self._get_git_version()
  File "/Library/Python/2.7/site-packages/repositoryhandler/backends/git.py", line 112, in _get_git_version
    self.git_version = tuple([int(i) for i in version.split('.')[0:3]])
ValueError: invalid literal for int() with base 10: '3 (Apple Git-50)\n'

Executing extensions
```

Executes on Mac OSX 10.9.5 
```
$ git --version
git version 1.9.3 (Apple Git-50)
```

**Comment by andygrunwald** [comment]
This was fixed in https://github.com/MetricsGrimoire/RepositoryHandler/commit/fde1f26764a4f3ee25487d0eb3ccf4d09faa4fa5
